apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev-issuer-staging
spec:
  acme:
    email: rafch@naver.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: dev-issuer-staging
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev-issuer
spec:
  acme:
    email: rafch@naver.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: dev-issuer
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
