apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: seol
  name: seol-chat-redis
spec:
  selector:
    matchLabels:
      app: seol-chat-redis
  serviceName: seol-chat-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: seol-chat-redis
    spec:
      containers:
        - name: seol-chat-redis
          image: redis:7-alpine
          env:
            - name: LC_ALL
              value: C.UTF-8
