apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.configMap.name }}
data:
  NODE_ENV: {{ .Values.configMap.node_env }}
  PORT: {{ .Values.configMap.port }}
  CHAT_WS_PATH: {{ .Values.configMap.chat_ws_path }}
