apiVersion: v1
kind: Endpoints
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app.name }}
subsets:
  - addresses:
      - ip: {{ .Values.app.ip }}
    ports:
      - port: {{ .Values.app.port }}
        protocol: TCP
