apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: seol
  name: seol-ingrses
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /chat-live
        backend:
          service:
            name: chat-live
            port:
              number: 8080
