apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secret.postgres_db }}
  POSTGRES_USER: {{ .Values.secret.postgres_user }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres_password }}
